site_name: Liberatube Docs
repo_url: https://github.com/golddominik893/liberatube
repo_name: golddominik893/liberatube


theme:
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

  name: material